name: Build Linux Repository

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu as the runner

    steps:
    - name: Checkout code
      uses
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dpkg-dev

    - name: Build Debian package
      run: |
        # Replace with your build commands to create .deb packages
        mkdir build_dir
        cp path/to/your/package/*.deb build_dir/


